#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/table_userma?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password:
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySql jdbc Driver
    url: jdbc:mysql://127.0.0.1:3306/table_userma?useSSL=false&requireSSL=false&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root   #本地设置数据库账号
    password:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
      # 连接数据库
      # eirunye_springboot_notes表示的是你创建的数据库;
      # useSSL:是否使用SSL证书验证;
      # characterEncoding:编码格式;
      # useJDBCCompliantTimezoneShift:是否使用符合JDBC的时区转换;
      # useLegacyDatetimeCode:是否使用旧版日期时间码;
      # serverTimezone:选择服务器时间方式;
    #  jpa:
    #    ##
    #    ##      hibernate:
    #    ##
    #    ##        ddl-auto: update
    #    ##
    #    ##      show-sql: tru
    #    ##    main:
    #    ##      allow-bean-definition-overriding: true
    show-sql: true
server:
  port: 8081
